### ISSUE TITLE
Kubernetes checklist

### ISSUE THREAD

**Issue by HarshadRanganathan** [HarshadRanganathan/harshadranganathan.github.io#108]
- [ ] Kickstart with Kubernetes, what and why?
- [ ] Intro to Kubernetes Objects & K8s Networking
- [ ] Kubernetes Infra Checklist
- [ ] Hands-on K8s Infra
- [ ] Provisioning managed k8s cluster ( Eksctl / TF )
- [ ] Provisioning self-managed K8s clusters ( KOps / Microk8s )
- [ ] Installing Devtron
- [ ] Setting up Infra essentials (Hands-on)
- [ ] Logging Stack (EFK)
- [ ] Monitoring Stack (Prometheus + Grafana)
- [ ] Cluster Autoscalers
- [ ] Ingress controller
- [ ] Setting up CI/CD pipelines for your microservice (Hands-on)
- [ ] Create CI/CD pipelines using Devtron
- [ ] Configuring and deploying your microservice
- [ ] Configure Ingress
- [ ] Configure autoscaling (CPU/RAM/External metrics)
- [ ] Making your microservice production ready

**Comment by HarshadRanganathan** [comment]
https://www.qovery.com/blog/7-common-kubernetes-pitfalls

**Comment by HarshadRanganathan** [comment]
https://newrelic.com/blog/how-to-relic/monitoring-kubernetes-part-two
